# Frontend Service
  - type: web
    name: email3-frontend
    region: oregon
    plan: free
    branch: main
    buildCommand: |
      npm install
      npm run build
      npm run export
    outputPath: out
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://email3-backend.onrender.com
    autoDeploy: true
