services:
  # Backend Service (FastAPI)
  - type: web
    name: email3-backend
    env: python
    region: oregon
    plan: free
    buildCommand: |
      pip install -r backend/requirements.txt
      playwright install chromium
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 10000
      - key: ENVIRONMENT
        value: production
    autoDeploy: true
    rootDir: backend

  # Frontend Service (Next.js)
  - type: web
    name: email3-frontend
    env: node
    plan: free
    buildCommand: |
      npm install
      npm run build
    startCommand: npm run start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://email3-backend.onrender.com
    rootDir: frontend
