services:
  # Backend (FastAPI)
  - type: web
    name: email3-backend
    env: python
    buildCommand: |
      pip install -r backend/requirements.txt
      cd backend && npm install  # Installs Playwright
    startCommand: uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 8000
      - key: ENVIRONMENT
        value: production
    plan: free

services:
  # Frontend (Next.js)
  - type: web
    name: email3-frontend
    env: node
    buildCommand: |
      cd frontend && npm ci && npm run build
    startCommand: |
      cd frontend && npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://email3-backend.onrender.com
    plan: free
