services:
  # Backend Service (Docker + Playwright)
  - type: web
    name: email3-backend
    env: docker
    dockerfilePath: backend/Dockerfile
    region: oregon
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /ms-playwright
    autoDeploy: true

  # Frontend Service
  - type: static_site
    name: email3-frontend
    region: oregon
    plan: free
    branch: main
    buildCommand: |
      npm install
      npm run build
      npm run export
    outputPath: out
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://email3-backend.onrender.com
    autoDeploy: true
