services:
  # Backend Service (Docker + Playwright)
  - type: web
    name: email3-backend
    env: docker
    dockerfilePath: backend/Dockerfile
    region: oregon
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /ms-playwright
    autoDeploy: true
